[build]
  publish = ".next"
  command = "NODE_OPTIONS=--max_old_space_size=4096 npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.deploy-preview.environment]
  NEXT_PUBLIC_WITHOUT_SESSION = "false"
  NODE_ENV = "development"
  ENV = "netlify"

[context.production.environment]
  NEXT_PUBLIC_WITHOUT_SESSION = "false"
  NODE_ENV = "development"

[functions]
  included_files = [
    "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/router-context*",
    "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/amp-context*",
    "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context*",
  ]