[build]
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.deploy-preview.environment]
  NEXT_PUBLIC_WITHOUT_SESSION = "false"
  NODE_ENV = "development"
  ENV = "netlify"

[context.production.environment]
  NEXT_PUBLIC_WITHOUT_SESSION = "false"
  NODE_ENV = "development"
