[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.deploy-preview.environment]
  BACKEND_URL = "https://incident-commander.canary.lab.flanksource.com/"
  NODE_ENV = "development"
  ENV = "netlify"

[context.production.environment]
  BACKEND_URL = "https://incident-commander.canary.lab.flanksource.com/"
  NODE_ENV = "development"
