name: Release
on:
  push:
    branches:
      - fix/canary-checker-ui-deployment
  pull_request:
    branches:
      - fix/canary-checker-ui-deployment

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.semantic.outputs.new_release_version }}
      new-release-published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - uses: actions/checkout@v3
      - uses: cycjimmy/semantic-release-action@v3
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: semantic-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deployment: [incident-manager-ui, canary-checker-ui]
    if: ${{ needs.semantic-release.outputs.new-release-published == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        env:
          APP_DEPLOYMENT: ${{ matrix.deployment == 'canary-checker-ui' && 'CANARY_CHECKER' || 'INCIDENT_MANAGER' }}
          WITHOUT_AUTH: ${{ matrix.deployment == 'canary-checker-ui' && 'true' || 'false' }}
        with:
          name: flanksource/${{ matrix.deployment }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: APP_DEPLOYMENT,WITHOUT_AUTH
          snapshot: true
          tags: "latest,v${{ needs.semantic-release.outputs.release-version }}"
